package AGM;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author giandoso
 */
public class AGM_panel extends javax.swing.JPanel {

    public Graphics2D g2d;
    public Kruskal k;
    public Graph g;

    /**
     * Creates new form AGM_panel
     */
    public AGM_panel() {
        initComponents();
        try {
            g = GraphPanel.getGraph();
            k = new Kruskal(g);
            System.out.println("Grafo e kruskal");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void paintComponent(Graphics gr) {
        super.paintComponent(gr);

        g2d = (Graphics2D) gr;
        k.run();
        List<Aresta> arestas = k.getX();
        System.out.println("");
        for (Aresta a : arestas) {
            System.out.println(a.getOrigem() + " -> " + a.getDestino());
            int xOrigem = (int) g.lista_vertices.get(a.getOrigem()).getX() * 5;
            int yOrigem = (int) g.lista_vertices.get(a.getOrigem()).getY() * 5;
            int xDestino = (int) g.lista_vertices.get(a.getDestino()).getX() * 5;
            int yDestino = (int) g.lista_vertices.get(a.getDestino()).getY() * 5;
            g2d.setColor(Color.BLACK);
            g2d.drawLine(xOrigem, yOrigem, xDestino, yDestino);
        }

        g2d.setColor(Color.red);

        for (double[] tupla : Reader.tuplas) {
            g2d.fillOval((int) (tupla[0] - 1) * 5, (int) (tupla[1] - 1) * 5, 7, 7);
        }

    }

    public void redraw() {
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
